/**
 * The icons `yarn icons` rasterises, as a value.
 *
 * Split out of `icons.ts` so it can be read without being run. That file opens
 * a Chromium and overwrites every PNG in `public/` from its top level, so a test
 * that imported it to ask which icons exist would regenerate them as a side
 * effect of asking.
 *
 * `tests/unit/manifest.test.ts` is what reads it, and reads it for a specific
 * reason: this list is the *namespace* of PWA icons. Comparing the manifest
 * against every PNG in `public/` instead would make any unrelated image added
 * there — a manifest screenshot, an Open Graph card — fail a suite whose
 * manifest is perfectly valid.
 */

/**
 * The theme's light background, copied from `--c-bg` in `src/index.css` and
 * from the `data-light` colour on the theme-color tag in `index.html`.
 *
 * Duplicated rather than imported because those are CSS and HTML, and because
 * an icon may not follow the reader's theme in any case: it is baked into a PNG
 * at build time and then sits on a home screen that has its own idea of light
 * and dark. The mark is the brand's, so it renders on the brand's surface.
 */
export const BACKGROUND = '#f7fbf9';

export interface IconSpec {
  file: string;
  size: number;
  /** How much of the canvas edge to edge the 48-unit mark is drawn across. */
  scale: number;
  /** An opaque surface behind the mark, or `null` to keep the PNG transparent. */
  background: string | null;
  /**
   * Whether `public/manifest.webmanifest` lists it.
   *
   * Not every icon here belongs there: iOS reads `<link rel="apple-touch-icon">`
   * and ignores `manifest.icons` entirely, so that one is generated by this file
   * and referenced only from `index.html`. Recorded as a field rather than left
   * to a reader to infer, because `tests/unit/manifest.test.ts` compares the two
   * lists and an exclusion written over there would be the same fact stated
   * twice, in the place least likely to be updated.
   */
  inManifest: boolean;
}

export const icons: readonly IconSpec[] = [
  // The two sizes Chromium requires before it will treat the manifest as
  // installable at all. Transparent, because these are composited onto surfaces
  // this file cannot see — a Windows taskbar, a ChromeOS shelf, an install
  // dialog in either theme — and the book green was already chosen dark enough
  // to hold its shape against a dark one.
  { file: 'icon-192.png', size: 192, scale: 0.9, background: null, inManifest: true },
  { file: 'icon-512.png', size: 512, scale: 0.9, background: null, inManifest: true },

  // Maskable, which is a different picture and not a resize of the one above.
  //
  // Android crops this to whatever shape the launcher uses — circle, squircle,
  // teardrop — and only the inner 80% circle is guaranteed to survive.
  //
  // 0.8 is measured against the shape the mark paints, not against its bounding
  // box: the box corners are empty — the leaves reach the top centre and the
  // book's outer edges sit well below them — and sizing to the box would inset
  // the icon by a fifth for margin nothing occupies. Measured on the generated
  // PNG, the furthest painted pixel sits 191px from the centre, inside the
  // 205px the safe circle allows.
  //
  // The surface is opaque, and that is not decoration: a transparent maskable
  // icon is cropped to a shape with nothing behind it, which is how a logo ends
  // up sitting on a black lozenge.
  {
    file: 'icon-maskable-512.png',
    size: 512,
    scale: 0.8,
    background: BACKGROUND,
    inManifest: true,
  },

  // iOS, which reads none of the above. It ignores an SVG favicon, ignores
  // `purpose`, applies its own rounded-rectangle mask, and composites any
  // transparency onto black — so this one is opaque too. Its mask takes the
  // corners and nothing else, and the mark reaches neither, so it is drawn
  // larger than the maskable one rather than to the same inset.
  {
    file: 'apple-touch-icon.png',
    size: 180,
    scale: 0.85,
    background: BACKGROUND,
    inManifest: false,
  },
];
