import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath, URL } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  FONT_FAMILIES,
  REMOVED_FAMILIES,
  assetsInlineLimit,
  isCoreFontFile,
  parseFontFile,
} from '../../font-config';

/**
 * The self-hosted fonts, at the layer that can see them without a build.
 *
 * `src/fonts.css` is generated by `yarn fonts` and committed, so nothing here
 * runs the generator — that would need the network, and would also make these
 * assertions about the script rather than about the file the app ships. What is
 * checked is the committed file against the spec it was generated from, which
 * is exactly the pair that drifts: regenerating is a manual step, and a family
 * added to `font-config.ts` without running it produces a build that silently
 * falls back for that family.
 *
 * Every failure below is silent in production. A missing `unicode-range` still
 * renders. A Google URL that came back still renders, until the policy is
 * promoted. An unused weight still renders, on somebody's phone data.
 */

const root = (path: string) => readFileSync(fileURLToPath(new URL(`../../${path}`, import.meta.url)), 'utf8'); // prettier-ignore

const fontsCss = root('src/fonts.css');
const indexHtml = root('index.html');
const indexCss = root('src/index.css');

interface Face {
  family: string;
  weight: number;
  /** The bare file name, which is what `isCoreFontFile` reads. */
  file: string;
  /** The specifier as written in the rule, which is what resolves to a file. */
  source: string;
  unicodeRange: string;
}

const faces: Face[] = [...fontsCss.matchAll(/@font-face \{([^}]*)\}/g)].map(([, body = '']) => ({
  family: /font-family: '([^']+)'/.exec(body)?.[1] ?? '',
  weight: Number(/font-weight: (\d+)/.exec(body)?.[1]),
  file: /files\/([^']+)/.exec(body)?.[1] ?? '',
  source: /url\('([^']+)'\)/.exec(body)?.[1] ?? '',
  unicodeRange: /unicode-range: ([^;]+);/.exec(body)?.[1] ?? '',
}));

describe('the generated stylesheet', () => {
  // Without this every loop below passes by iterating over nothing, which is
  // the shape of a suite that is green because the file failed to parse.
  it('parses into the rules it claims to have', () => {
    expect(faces.length).toBeGreaterThan(300);
    expect(faces.every((face) => face.family && face.weight && face.file && face.source)).toBe(
      true,
    );
  });

  it.each(['fonts.googleapis.com', 'fonts.gstatic.com'])(
    "never reaches %s, which `font-src 'self'` forbids and a worker can only cache blind",
    (host) => {
      // Both halves of #81 at once. The policy in `firebase.json` is deployed
      // Report-Only, so a host that came back would fetch happily and break on
      // the day the policy is promoted — and until then the worker sees an
      // opaque response it cannot validate, which is the offline gap.
      //
      // Asserted against each rule's `src` rather than the file's text, because
      // the generated header names the host it copies the ranges *from* — and a
      // test that read that as a fetch would be red on a file that is correct.
      for (const face of faces) expect(face.source).not.toContain(host);
      expect(indexHtml).not.toContain(host);
      expect(indexCss).not.toContain(host);
    },
  );

  it('gives every face a unicode-range, without which one screen of Japanese costs 1.5 MB', () => {
    // The single reason this file is 363 rules rather than 7. A face that lost
    // its range covers the whole subset, so the browser fetches the entire
    // 1.5 MB Japanese file to draw one heading — and nothing about that is
    // visible except in a network panel.
    for (const face of faces) {
      expect(face.unicodeRange, `${face.file} has no unicode-range`).toMatch(/U\+/);
    }
  });

  it('points every rule at a file that exists, so a version bump cannot fail silently', () => {
    // Fontsource and Google have to agree on how the family was subsetted for
    // the chunk numbers to line up. When they stop agreeing the rule points at
    // nothing, the browser falls back, and the app looks fine to whoever ran
    // the build on a machine where the old file was still in `node_modules`.
    for (const face of faces) {
      const path = fileURLToPath(new URL(`../../node_modules/${face.source}`, import.meta.url));
      expect(existsSync(path), `${face.file} is missing from node_modules`).toBe(true);
    }
  });

  it.each(FONT_FAMILIES.flatMap((f) => f.weights.map((w) => [f.family, w.weight] as const)))(
    'has rules for %s %d, so a family added to the spec cannot ship unregenerated',
    (family, weight) => {
      // `yarn fonts` is a manual step. Adding a weight to `font-config.ts` and
      // forgetting to run it produces a build that falls back for that weight
      // and reports nothing.
      expect(faces.some((face) => face.family === family && face.weight === weight)).toBe(true);
    },
  );

  it.each(REMOVED_FAMILIES)(
    'does not self-host %s, whose removal is the point of the change',
    (family) => {
      // `Noto Sans TC` drew Japanese prose in Traditional Chinese character
      // forms — 花 with the four-stroke 艹, 骨 with its box mirrored. Bringing it
      // back as a self-hosted face would restore the defect *and* 3 MB.
      expect(fontsCss).not.toContain(`font-family: '${family}'`);
    },
  );

  it('never ships Zen Maru Gothic 900, which nothing in src has ever set', () => {
    // Requested from Google for as long as the app has existed, and used by no
    // `font-black`, no `font-extrabold` and no `font-weight` anywhere. 1.5 MB
    // that was downloaded and never drawn a glyph.
    expect(faces.some((face) => face.family === 'Zen Maru Gothic' && face.weight === 900)).toBe(
      false,
    );
  });
});

describe('which files the worker precaches', () => {
  const zenMaru = (chunk: number, weight: number) => `zen-maru-gothic-${chunk}-${weight}-normal.woff2`; // prettier-ignore

  it.each([500, 700])(
    'precaches the kana chunk for Zen Maru %d, which every furigana needs',
    (weight) => {
      // Chunk 119 is kana and full-width punctuation. It is what draws every
      // `<rt>` in the app, so a reader offline without it sees annotations in the
      // platform face above headwords in Zen Maru — two faces in one word.
      expect(isCoreFontFile(zenMaru(119, weight))).toBe(true);
    },
  );

  it('leaves the long tail out, without which the precache is 6.8 MB rather than 2.9', () => {
    // Chunk 5 is deep in the rare end of Google's frequency ordering. If this
    // is precached then so is everything above it, and the split has stopped
    // splitting — which nothing fails on, it just costs every reader megabytes.
    expect(isCoreFontFile(zenMaru(5, 700))).toBe(false);
  });

  it('precaches the headword weight further down than the prose weight', () => {
    // The asymmetry in `font-config.ts` is deliberate: 700 is the headword, and
    // a headword in the wrong face is a change to what the reader came to look
    // at. Flattening the two bounds to one number would quietly undo that.
    const headword = FONT_FAMILIES.find((f) => f.family === 'Zen Maru Gothic')?.weights.find((w) => w.weight === 700); // prettier-ignore
    const prose = FONT_FAMILIES.find((f) => f.family === 'Noto Sans JP')?.weights.find((w) => w.weight === 400); // prettier-ignore
    expect(headword?.coreFrom).toBeLessThan(prose?.coreFrom ?? 0);
  });

  it('precaches every named subset, which is where the Latin interface lives', () => {
    // `latin` has no frequency rank to compare against, so the rank test must
    // not be reached for it at all — a `NaN` comparison would answer false and
    // put the interface's own face behind a runtime fetch.
    expect(isCoreFontFile('inter-latin-400-normal.woff2')).toBe(true);
    expect(isCoreFontFile('zen-maru-gothic-latin-700-normal.woff2')).toBe(true);
  });

  it('keeps every chunk a file, since an inlined one belongs to whatever precaches the CSS', () => {
    // Measured, not feared: with Vite's 4 KiB default, twelve `Zen Maru Gothic`
    // chunks were emitted into neither directory. They went into `index.css` as
    // `data:` URIs, and `index.css` is precached — so the split silently handed
    // twelve of the runtime half to every reader, base64 and a third larger.
    // `dist` had 351 woff2 against 363 rules, and nothing said so.
    expect(assetsInlineLimit('assets/zen-maru-gothic-2-500-normal.woff2')).toBe(false);
    // Everything else keeps Vite's own rule, which the small SVGs rely on.
    expect(assetsInlineLimit('assets/favicon.svg')).toBeUndefined();
  });

  it('answers false for a font it does not ship, rather than precaching the unknown', () => {
    expect(isCoreFontFile('some-other-font-400-normal.woff2')).toBe(false);
    expect(isCoreFontFile('index-a1b2c3.js')).toBe(false);
  });

  it('reads a hyphenated subset name back without swallowing it into the package', () => {
    // `zen-maru-gothic-latin-ext-500-normal.woff2` is the case a greedy split
    // gets wrong: it reads the package as `zen-maru-gothic-latin` and the
    // subset as `ext`, and the file then falls out of the spec entirely.
    expect(parseFontFile('zen-maru-gothic-latin-ext-500-normal.woff2')).toEqual({
      fontsourcePackage: 'zen-maru-gothic',
      chunk: null,
      weight: 500,
    });
    expect(parseFontFile('zen-maru-gothic-119-500-normal.woff2')).toEqual({
      fontsourcePackage: 'zen-maru-gothic',
      chunk: 119,
      weight: 500,
    });
  });
});
